name: Pull Request Automation

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set destination branch
        run: echo "DESTINATION_BRANCH=main" >> $GITHUB_ENV

      - name: Get commit messages
        run: |
          git fetch --depth=1 origin main
          commit_messages=$(git log --pretty=format:"%s" HEAD..origin/main)
          echo "::set-output name=commit-messages::$commit_messages"

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "develop"
          destination_branch: "main"
          pr_title: "Pull request ${{ github.head_ref }} into ${{ env.DESTINATION_BRANCH }}"
          pr_body: "Automated pull request with the following commits:\n${{ steps.get-commit-messages.outputs.commit-messages }}"
          pr_label: "feature, automated pr"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}