name: Pull Request Action

on:
  push:
    branches:
      - feature/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set destination branch
        run: echo "DESTINATION_BRANCH=develop" >> $GITHUB_ENV

      - name: Get commit messages
        id: get-commit-messages
        run: |
          COMMIT_MESSAGES=$(git log --pretty=format:"%s" -10)
          echo "COMMIT_MESSAGES=$COMMIT_MESSAGES" >> $GITHUB_ENV

      - name: Debug PR body
        run: |
          echo "PR_BODY:" 
          cat $GITHUB_EVENT_PATH
        if: always()

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: develop
          pr_title: "Pull request ${{ github.head_ref }} into ${{ env.DESTINATION_BRANCH }}"
          pr_body: "Automated pull request with the following commits:\n${{ steps.get-commit-messages.outputs.COMMIT_MESSAGES }}"
          pr_label: "feature, automated pr"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
