name: Pull Request Action
on:
  push:
    branches:
      - feature/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          token: ${{ secrets.PERSONAL_TOKEN }}
          pr_title: "Merge ${{ github.ref_name }} into develop"
          pr_body: "This is an automated pull request from ${{ github.ref_name }} to develop."
          pr_label: "feature, automated pr"