name: Pull Request Action Dev To Main
on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          token: ${{ secrets.PERSONAL_TOKEN }}
          pr_label: "feature, automated pr"
          pr_title: "[Example] Simple demo"