name: Pull Request Action Dev To Main

on:
  push:
    branches:
      - develop

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "develop"
          destination_branch: "main"
          pr_title: "Merge ${{ github.ref_name }} into main"
          pr_body: "This is an automated pull request from ${{ github.ref_name }} to main."
          pr_label: "feature, automated pr"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}