name: Pull Request Action
on:
  push:
    branches:
      - feature/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          token: ${{ secrets.PERSONAL_TOKEN }}
          pr_label: "PR Featture to DEV"
          pr_title: "PR Featture to DEV"